# Generated by Django 3.1.4 on 2021-01-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('wagtail_wordpress_importer', '0002_historicalimportpost_importpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_total', models.PositiveIntegerField(default=0)),
                ('category_api', models.PositiveIntegerField(default=0)),
                ('setting_total', models.PositiveIntegerField(default=0)),
                ('setting_api', models.PositiveIntegerField(default=0)),
                ('region_total', models.PositiveIntegerField(default=0)),
                ('region_api', models.PositiveIntegerField(default=0)),
                ('publication_type_total', models.PositiveIntegerField(default=0)),
                ('publication_type_api', models.PositiveIntegerField(default=0)),
                ('post_total', models.PositiveIntegerField(default=0)),
                ('post_api', models.PositiveIntegerField(default=0)),
                ('page_total', models.PositiveIntegerField(default=0)),
                ('page_api', models.PositiveIntegerField(default=0)),
                ('blog_total', models.PositiveIntegerField(default=0)),
                ('blog_api', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
