# Generated by Django 3.1.4 on 2021-01-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0004_report_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
