# Generated by Django 3.1.4 on 2021-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0006_historicalimportatlascasestudy_importatlascasestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportatlascasestudy',
            name='publication_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalimportatlascasestudy',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importatlascasestudy',
            name='publication_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importatlascasestudy',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
