# Generated by Django 3.1.4 on 2021-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0008_historicalimportdocument_importdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportdocument',
            name='improvement_challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalimportdocument',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importdocument',
            name='improvement_challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importdocument',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
    ]
