# Generated by Django 3.1.4 on 2021-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0010_historicalimportmedia_importmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalimportmedia',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Media'},
        ),
        migrations.AlterModelOptions(
            name='importmedia',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterField(
            model_name='historicalimportmedia',
            name='post',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='importmedia',
            name='post',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
