# Generated by Django 3.1.4 on 2021-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0011_auto_20210107_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimportmedia',
            name='post',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importmedia',
            name='post',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
