# Generated by Django 3.1.4 on 2021-01-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0012_auto_20210107_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportmedia',
            name='source_404',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importmedia',
            name='source_404',
            field=models.BooleanField(default=False),
        ),
    ]
