# Generated by Django 3.1.4 on 2021-01-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0015_customfieldsgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfieldsgroup',
            options={'verbose_name': 'Custom Fields Group', 'verbose_name_plural': 'Custom Fields Groups'},
        ),
    ]
