# Generated by Django 3.1.4 on 2021-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0018_customfieldsgroup_sub_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldsgroup',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
