# Generated by Django 3.1.4 on 2021-01-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0019_auto_20210109_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldsgroup',
            unique_together={('key', 'sub_site')},
        ),
    ]
