# Generated by Django 3.1.4 on 2021-01-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0020_auto_20210109_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldsGroupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(blank=True, max_length=50)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('order_no', models.CharField(blank=True, max_length=50)),
                ('group_no', models.CharField(blank=True, max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields_groups', to='wagtail_wordpress_importer.customfieldsgroup')),
            ],
            options={
                'verbose_name': 'Group Location',
                'verbose_name_plural': 'Group Locations',
                'ordering': ['group'],
            },
        ),
    ]
