# Generated by Django 3.1.4 on 2021-01-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0021_customfieldsgrouplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldsgrouplocation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields_locations', to='wagtail_wordpress_importer.customfieldsgroup'),
        ),
    ]
