# Generated by Django 3.1.4 on 2021-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0022_auto_20210109_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldsgrouplocation',
            name='group_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customfieldsgrouplocation',
            name='order_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
