# Generated by Django 3.1.4 on 2021-01-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0023_auto_20210109_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfieldsgrouplocation',
            options={'ordering': ['group'], 'verbose_name': 'Custom Fields Group Location', 'verbose_name_plural': 'Custom Fields Group Locations'},
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='wagtail_wordpress_importer.customfieldsgroup')),
            ],
            options={
                'verbose_name': 'Custom Fields Field',
                'verbose_name_plural': 'Custom Fields Fields',
                'ordering': ['label'],
            },
        ),
    ]
