# Generated by Django 3.1.4 on 2021-01-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0024_auto_20210109_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='button_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='collapsed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='conditional_logic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='customfield',
            name='instuctions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='layout',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customfield',
            name='menu_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customfield',
            name='min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customfield',
            name='parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='customfield',
            name='sub_fields',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='wp_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='wrapper',
            field=models.TextField(blank=True),
        ),
    ]
