# Generated by Django 3.1.4 on 2021-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0025_auto_20210109_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='sub_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
