# Generated by Django 3.1.4 on 2021-01-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0028_auto_20210109_2213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('key', 'sub_site')},
        ),
    ]
