# Generated by Django 3.1.4 on 2021-01-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0029_auto_20210109_2214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('group', 'key', 'sub_site')},
        ),
    ]
