# Generated by Django 3.1.4 on 2021-01-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0030_auto_20210109_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('key', 'sub_site')},
        ),
    ]
