# Generated by Django 3.1.4 on 2021-01-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0031_auto_20210109_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='max',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='min',
            field=models.IntegerField(blank=True),
        ),
    ]
