# Generated by Django 3.1.4 on 2021-01-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0034_auto_20210109_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='max',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='min',
        ),
    ]
