# Generated by Django 3.1.4 on 2021-01-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0036_auto_20210109_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['group'], 'verbose_name': 'Custom Fields Field', 'verbose_name_plural': 'Custom Fields Fields'},
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='sub_fields',
            new_name='field',
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='_type',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='_valid',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='collapsed',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='conditional_logic',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='instuctions',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='key',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='menu_order',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='sub_site',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='value',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='wp_id',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='wrapper',
        ),
    ]
