# Generated by Django 3.1.4 on 2021-01-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0039_auto_20210109_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['group'], 'verbose_name': 'Custom Field', 'verbose_name_plural': 'Custom Fields'},
        ),
        migrations.AlterModelOptions(
            name='customfieldsgroup',
            options={'verbose_name': 'Custom Group', 'verbose_name_plural': 'Custom Groups'},
        ),
        migrations.AlterModelOptions(
            name='customfieldsgrouplocation',
            options={'ordering': ['group'], 'verbose_name': 'Custom Group Location', 'verbose_name_plural': 'Custom Group Locations'},
        ),
        migrations.AddField(
            model_name='customfield',
            name='key',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
