# Generated by Django 3.1.4 on 2021-01-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0040_auto_20210109_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldsgroup',
            name='location',
            field=models.JSONField(blank=True),
        ),
    ]
