# Generated by Django 3.1.4 on 2021-01-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0041_auto_20210110_0628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFieldsGroupLocation',
        ),
    ]
