# Generated by Django 3.1.4 on 2021-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0042_delete_customfieldsgrouplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimportblog',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='importblog',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
    ]
