# Generated by Django 3.1.4 on 2021-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0043_auto_20210110_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimportdocument',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='importdocument',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
    ]
