# Generated by Django 3.1.4 on 2021-01-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0044_auto_20210110_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimportmedia',
            name='media_details',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='importmedia',
            name='media_details',
            field=models.JSONField(blank=True),
        ),
    ]
