# Generated by Django 3.1.4 on 2021-01-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0045_auto_20210110_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimportpage',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='importpage',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
    ]
