# Generated by Django 3.1.4 on 2021-01-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0046_auto_20210110_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimportpost',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='importpost',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
    ]
