# Generated by Django 3.1.4 on 2021-01-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0047_auto_20210110_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimportatlascasestudy',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='importatlascasestudy',
            name='custom_fields',
            field=models.JSONField(blank=True),
        ),
    ]
