# Generated by Django 3.1.4 on 2021-01-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0049_customfieldjsonvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldjsonvalues',
            name='_field',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='wagtail_wordpress_importer.customfield'),
            preserve_default=False,
        ),
    ]
