# Generated by Django 3.1.4 on 2021-01-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0054_auto_20210111_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={},
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='json_field',
        ),
        migrations.AddField(
            model_name='customfield',
            name='_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customfield',
            name='fields_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wagtail_wordpress_importer.customfieldsgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfield',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customfield',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomFieldJsonValues',
        ),
    ]
