# Generated by Django 3.1.4 on 2021-01-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0055_auto_20210111_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldsGroupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_key', models.CharField(blank=True, max_length=100)),
                ('_value', models.CharField(blank=True, max_length=100)),
                ('fields_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtail_wordpress_importer.customfieldsgroup')),
            ],
        ),
    ]
