# Generated by Django 3.1.4 on 2021-01-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0056_customfieldsgrouplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldsgrouplocation',
            name='_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
