# Generated by Django 3.1.4 on 2021-01-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0057_customfieldsgrouplocation__index'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='sub_fields',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
