# Generated by Django 3.1.4 on 2021-01-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0059_customfieldslayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'verbose_name': 'Custom Field', 'verbose_name_plural': 'Custom Fields'},
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('key', 'sub_site')},
        ),
    ]
