# Generated by Django 3.1.4 on 2021-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0061_customfield_layouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_layout',
            field=models.BooleanField(default=False),
        ),
    ]
