# Generated by Django 3.1.4 on 2021-01-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0064_customfield_layout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfieldslayout',
            old_name='_type',
            new_name='display',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtail_wordpress_importer.customfieldslayout'),
        ),
    ]
