# Generated by Django 3.1.4 on 2021-01-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0066_auto_20210111_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldsLayoutSubField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_key', models.CharField(blank=True, max_length=100)),
                ('_value', models.CharField(blank=True, max_length=100)),
                ('_index', models.PositiveIntegerField(default=0)),
                ('fields_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtail_wordpress_importer.customfieldslayout')),
            ],
        ),
    ]
