# Generated by Django 3.1.4 on 2021-01-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0067_customfieldslayoutsubfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfieldslayoutsubfield',
            old_name='fields_group',
            new_name='fields_layout',
        ),
    ]
