# Generated by Django 3.1.4 on 2021-01-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0070_customfieldslayoutsubfield_custom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldslayoutsubfield',
            name='custom_field',
        ),
    ]
