# Generated by Django 3.1.4 on 2021-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0071_remove_customfieldslayoutsubfield_custom_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportmedia',
            name='file_parts',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importmedia',
            name='file_parts',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
