# Generated by Django 3.1.4 on 2021-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0072_auto_20210111_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
