# Generated by Django 3.1.4 on 2021-01-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0073_customfield_usage_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPageCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100)),
                ('import_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtail_wordpress_importer.importpage')),
            ],
        ),
    ]
