# Generated by Django 3.1.4 on 2021-01-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0074_importpagecustomfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importpagecustomfield',
            options={'verbose_name': 'Page Custom', 'verbose_name_plural': 'Pages Custom'},
        ),
        migrations.AddField(
            model_name='importpagecustomfield',
            name='sub_site',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
