# Generated by Django 3.1.4 on 2021-01-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wordpress_importer', '0078_auto_20210112_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterImportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtail_wordpress_importer.importcategory')),
            ],
        ),
    ]
